/**
 * Shared fast-check generators (arbitraries) for the sprint runner's
 * property-based tests.
 *
 * This module is *not* a test file — it has no `.test.ts` suffix and is
 * excluded from vitest's include globs. It exists to keep the domain-type
 * generators in one place so every property test shares the same
 * shrinking strategy and value space.
 *
 * Requirements: supports all sprint-runner property tests (Properties 1–14)
 */

import fc from "fast-check";

import type {
  AgentRole,
  CustomerPersona,
  FileChange,
  FileChangeOperation,
  FindingCategory,
  FindingSeverity,
  FixStatus,
  SprintStatus,
} from "../types";
import {
  AGENT_ROLES,
  CUSTOMER_PERSONAS,
  FILE_CHANGE_OPERATIONS,
  FINDING_CATEGORIES,
  FINDING_SEVERITIES,
  FIX_STATUSES,
  SPRINT_STATUSES,
} from "../types";
import {
  SPRINT_STATE_EVENT_TYPES,
  type SprintStateEvent,
  type SprintStateEventType,
} from "../state-guard";

// ---------------------------------------------------------------------------
// Enum arbitraries
// ---------------------------------------------------------------------------

export const agentRoleArb: fc.Arbitrary<AgentRole> = fc.constantFrom(
  ...AGENT_ROLES,
);

export const customerPersonaArb: fc.Arbitrary<CustomerPersona> = fc.constantFrom(
  ...CUSTOMER_PERSONAS,
);

export const findingCategoryArb: fc.Arbitrary<FindingCategory> = fc.constantFrom(
  ...FINDING_CATEGORIES,
);

export const findingSeverityArb: fc.Arbitrary<FindingSeverity> = fc.constantFrom(
  ...FINDING_SEVERITIES,
);

export const sprintStatusArb: fc.Arbitrary<SprintStatus> = fc.constantFrom(
  ...SPRINT_STATUSES,
);

export const fixStatusArb: fc.Arbitrary<FixStatus> = fc.constantFrom(
  ...FIX_STATUSES,
);

export const fileChangeOperationArb: fc.Arbitrary<FileChangeOperation> =
  fc.constantFrom(...FILE_CHANGE_OPERATIONS);

// ---------------------------------------------------------------------------
// Identifier generators
// ---------------------------------------------------------------------------

/** 24-char hex string, shaped like a Mongo ObjectId. */
export const objectIdHexArb: fc.Arbitrary<string> = fc
  .array(
    fc.integer({ min: 0, max: 15 }).map((n) => n.toString(16)),
    { minLength: 24, maxLength: 24 },
  )
  .map((chars) => chars.join(""));

/** Kebab-case-ish repo-relative path, e.g. `src/foo/bar.ts`. */
export const repoRelativePathArb: fc.Arbitrary<string> = fc
  .array(
    fc
      .string({ minLength: 1, maxLength: 16 })
      .map((s) => s.replace(/[^a-zA-Z0-9_-]/g, "") || "x"),
    { minLength: 1, maxLength: 5 },
  )
  .map((parts) => `src/${parts.join("/")}.ts`);

// ---------------------------------------------------------------------------
// FileChange arbitrary
//
// Shape matches the FileChange interface in types.ts. Line counts are
// bounded so the spec-emitter property test can efficiently explore both
// "promote" and "don't promote" sides of the line-count threshold (500).
// ---------------------------------------------------------------------------

export const fileChangeArb: fc.Arbitrary<FileChange> = fc.record({
  path: repoRelativePathArb,
  operation: fileChangeOperationArb,
  addedLines: fc.integer({ min: 0, max: 2000 }),
  removedLines: fc.integer({ min: 0, max: 2000 }),
  diff: fc.string({ maxLength: 200 }),
});

// ---------------------------------------------------------------------------
// Finding arbitrary
//
// Matches the fields of `IFinding` that are meaningful for property tests
// (id, category, severity, title, description, reproductionSteps,
// evidenceUrls). The Mongo-only fields (`_id`, `sprintId`, `dedupSignature`,
// `duplicateCount`, `createdAt`) are omitted — those are computed by the
// runner, not generated by agents.
// ---------------------------------------------------------------------------

export interface FindingArbShape {
  readonly id: string;
  readonly category: FindingCategory;
  readonly severity: FindingSeverity;
  readonly title: string;
  readonly description: string;
  readonly reproductionSteps: readonly string[];
  readonly evidenceUrls: readonly string[];
}

export const findingArb: fc.Arbitrary<FindingArbShape> = fc.record({
  id: fc
    .tuple(
      fc
        .string({ minLength: 6, maxLength: 6 })
        .map((s) => s.replace(/[^a-z0-9]/g, "a").toLowerCase()),
      fc.integer({ min: 1, max: 9999 }),
    )
    .map(([short, seq]) => `F-${short}-${seq}`),
  category: findingCategoryArb,
  severity: findingSeverityArb,
  title: fc.string({ minLength: 1, maxLength: 80 }).map((s) => s.trim() || "t"),
  description: fc
    .string({ minLength: 1, maxLength: 240 })
    .map((s) => s.trim() || "d"),
  reproductionSteps: fc.array(
    fc.string({ minLength: 1, maxLength: 80 }).map((s) => s.trim() || "s"),
    { minLength: 1, maxLength: 5 },
  ),
  evidenceUrls: fc.array(fc.webUrl(), { minLength: 0, maxLength: 3 }),
});

// ---------------------------------------------------------------------------
// FixProposal arbitrary
//
// Matches the fields of `IFixProposal` that the rule-layer tests need:
// id, findingIds, title, authorAgentRole, fileChanges, status. The
// proposal id format mirrors the P-<sprint_short>-<seq> pattern from the
// design doc.
// ---------------------------------------------------------------------------

export interface FixProposalArbShape {
  readonly id: string;
  readonly findingIds: readonly string[];
  readonly title: string;
  readonly authorAgentRole: AgentRole;
  readonly fileChanges: readonly FileChange[];
  readonly status: FixStatus;
}

export const fixProposalArb: fc.Arbitrary<FixProposalArbShape> = fc.record({
  id: fc
    .tuple(
      fc
        .string({ minLength: 6, maxLength: 6 })
        .map((s) => s.replace(/[^a-z0-9]/g, "a").toLowerCase()),
      fc.integer({ min: 1, max: 999 }),
    )
    .map(([short, seq]) => `P-${short}-${seq}`),
  findingIds: fc.array(
    fc
      .tuple(
        fc
          .string({ minLength: 6, maxLength: 6 })
          .map((s) => s.replace(/[^a-z0-9]/g, "a").toLowerCase()),
        fc.integer({ min: 1, max: 9999 }),
      )
      .map(([short, seq]) => `F-${short}-${seq}`),
    { minLength: 0, maxLength: 6 },
  ),
  title: fc
    .string({ minLength: 1, maxLength: 80 })
    .map((s) => s.trim() || "fix"),
  authorAgentRole: agentRoleArb,
  fileChanges: fc.array(fileChangeArb, { minLength: 0, maxLength: 25 }),
  status: fixStatusArb,
});

// ---------------------------------------------------------------------------
// Sprint state event arbitraries — consumed by the state-guard property test.
//
// `sprintStateEventTypeArb` generates only the event-type discriminant;
// `sprintStateEventArb` generates a fully-formed `SprintStateEvent` record
// (including the `ctx` payload for `start`).
// ---------------------------------------------------------------------------

export const sprintStateEventTypeArb: fc.Arbitrary<SprintStateEventType> =
  fc.constantFrom(...SPRINT_STATE_EVENT_TYPES);

const startContextArb = fc.record({
  anotherSprintRunning: fc.boolean(),
  envLoaded: fc.boolean(),
});

export const sprintStateEventArb: fc.Arbitrary<SprintStateEvent> =
  sprintStateEventTypeArb.chain((type) => {
    if (type === "start") {
      return startContextArb.map(
        (ctx) => ({ type: "start", ctx }) as SprintStateEvent,
      );
    }
    return fc.constant({ type } as SprintStateEvent);
  });
